{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "setting cwd to '/mnt/samba/research/shield/projects/payamfz/medical-ssl-segmentation'\n",
      "['/mnt/samba/research/shield/projects/payamfz/medical-ssl-segmentation/mycode/jupyter', '/home/payam/miniconda3/envs/tf2-gpu/lib/python39.zip', '/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9', '/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/lib-dynload', '', '/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages', '/mnt/samba/research/shield/projects/payamfz/medical-ssl-segmentation/mycode']\n",
      "/mnt/samba/research/shield/projects/payamfz/medical-ssl-segmentation\n"
     ]
    }
   ],
   "source": [
    "# set project root to correct path\n",
    "import sys\n",
    "import os\n",
    "\n",
    "proj_path = '/mnt/samba/research/shield/projects/payamfz/medical-ssl-segmentation/mycode'\n",
    "if proj_path not in sys.path:\n",
    "  sys.path.append(proj_path)\n",
    "\n",
    "from set_path import set_path\n",
    "set_path()\n",
    "\n",
    "print(sys.path)\n",
    "print(os.getcwd())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-03-06 21:14:33.815366: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-03-06 21:14:34.434847: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-12.3/lib64:/home/payam/miniconda3/envs/tf2-gpu/lib/\n",
      "2024-03-06 21:14:34.434920: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-12.3/lib64:/home/payam/miniconda3/envs/tf2-gpu/lib/\n",
      "2024-03-06 21:14:34.434928: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n"
     ]
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import numpy as np\n",
    "\n",
    "from loader.mimic_cxr_jpg_loader import MIMIC_CXR_JPG_Loader\n",
    "from utils.augmentation import preprocess_image\n",
    "\n",
    "BATCH_SIZE = 5\n",
    "\n",
    "def _preprocess(x, y, info=None):\n",
    "    out = {}\n",
    "    out['image'] = preprocess_image(\n",
    "        x, 448, 448, is_training=False, color_distort=False, crop='Center')\n",
    "    out['label'] = y\n",
    "    out['info'] = info\n",
    "    return out\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "merged_data                                        dicom_id subject_id  study_id  \\\n",
      "0  02aa804e-bde0afdd-112c0b34-7bc16630-4e384014   10000032  50414267   \n",
      "1  174413ec-4ec4c1f7-34ea26b7-c5f994f8-79ef1962   10000032  50414267   \n",
      "2  2a2277a9-b0ded155-c0de8eb9-c124d10e-82c5caab   10000032  53189527   \n",
      "3  e084de3b-be89b11e-20fe3f9f-9c8d8dfe-4cfd202c   10000032  53189527   \n",
      "4  68b5c4b1-227d0485-9cc38c3f-7b84ab51-4b472714   10000032  53911762   \n",
      "\n",
      "  PerformedProcedureStepDescription ViewPosition  Rows Columns StudyDate  \\\n",
      "0                CHEST (PA AND LAT)           PA  3056    2544  21800506   \n",
      "1                CHEST (PA AND LAT)      LATERAL  3056    2544  21800506   \n",
      "2                CHEST (PA AND LAT)           PA  3056    2544  21800626   \n",
      "3                CHEST (PA AND LAT)      LATERAL  3056    2544  21800626   \n",
      "4               CHEST (PORTABLE AP)           AP  2705    2539  21800723   \n",
      "\n",
      "            StudyTime ProcedureCodeSequence_CodeMeaning  \\\n",
      "0  213014.53100000002                CHEST (PA AND LAT)   \n",
      "1  213014.53100000002                CHEST (PA AND LAT)   \n",
      "2          165500.312                CHEST (PA AND LAT)   \n",
      "3          165500.312                CHEST (PA AND LAT)   \n",
      "4           80556.875               CHEST (PORTABLE AP)   \n",
      "\n",
      "  ViewCodeSequence_CodeMeaning PatientOrientationCodeSequence_CodeMeaning  \\\n",
      "0             postero-anterior                                      Erect   \n",
      "1                      lateral                                      Erect   \n",
      "2             postero-anterior                                      Erect   \n",
      "3                      lateral                                      Erect   \n",
      "4             antero-posterior                                              \n",
      "\n",
      "   split  \n",
      "0  train  \n",
      "1  train  \n",
      "2  train  \n",
      "3  train  \n",
      "4  train  \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-03-06 21:14:42.950711: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2024-03-06 21:14:42.985034: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2024-03-06 21:14:42.985322: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2024-03-06 21:14:42.986008: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2024-03-06 21:14:42.986868: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2024-03-06 21:14:42.987012: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2024-03-06 21:14:42.987137: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2024-03-06 21:14:43.423829: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2024-03-06 21:14:43.424006: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2024-03-06 21:14:43.424134: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
      "2024-03-06 21:14:43.424250: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10399 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From /home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/autograph/pyct/static_analysis/liveness.py:83: Analyzer.lamba_check (from tensorflow.python.autograph.pyct.static_analysis.liveness) is deprecated and will be removed after 2023-09-23.\n",
      "Instructions for updating:\n",
      "Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089\n",
      "{'num_classes': 7, 'class_names': array(['Atelectasis', 'Cardiomegaly', 'Consolidation', 'Edema',\n",
      "       'Pleural Effusion', 'Pneumonia', 'Pneumothorax'], dtype='<U16'), 'total_size': 377110, 'split_size': {'train': 1000, 'validate': 100, 'test': 100}, 'split_size_frac': {'train': 0.002651746174856143, 'validate': 0.00026517461748561426, 'test': 0.00026517461748561426}}\n"
     ]
    }
   ],
   "source": [
    "myCustomDataLoader = MIMIC_CXR_JPG_Loader({'train': 1000, 'validate': 100, 'test': 100})\n",
    "train_tfds, val_tfds, test_tfds = myCustomDataLoader.load()\n",
    "class_names = myCustomDataLoader.info()['class_names']\n",
    "print(myCustomDataLoader.metadata)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# TEST 1: ------- Test Train dataset -------\n",
    "batched_tfds = train_tfds.shuffle(buffer_size=2*BATCH_SIZE).map(_preprocess).batch(BATCH_SIZE)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "# TEST 2: ------- Test Validation dataset -------\n",
    "batched_tfds = val_tfds.shuffle(buffer_size=2*BATCH_SIZE).map(_preprocess).batch(BATCH_SIZE)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "v10\n",
      "merged_data                                         dicom_id subject_id  study_id  \\\n",
      "7   096052b7-d256dc40-453a102b-fa7d01c6-1b22c6b4   10000764  57375967   \n",
      "8   b79e55c3-735ce5ac-64412506-cdc9ea79-f1af521f   10000764  57375967   \n",
      "9   dcfeeac4-1597e318-d0e6736a-8b2c2238-47ac3f1b   10000764  57375967   \n",
      "15  d0b71acc-b5a62046-bbb5f6b8-7b173b85-65cdf738   10000935  50578979   \n",
      "27  943486a3-b3fa9ff7-50f5a769-7a62fcbb-f39b6da4   10000980  51967283   \n",
      "\n",
      "   PerformedProcedureStepDescription ViewPosition  Rows Columns StudyDate  \\\n",
      "7                 CHEST (PA AND LAT)           AP  2544    3056  21321015   \n",
      "8                 CHEST (PA AND LAT)      LATERAL  3056    2544  21321015   \n",
      "9                 CHEST (PA AND LAT)      LATERAL  3056    2544  21321015   \n",
      "15               CHEST (PORTABLE AP)           AP  2870    2402  21871016   \n",
      "27               CHEST (PORTABLE AP)           AP  3056    2544  21890627   \n",
      "\n",
      "             StudyTime ProcedureCodeSequence_CodeMeaning  \\\n",
      "7            84047.984                CHEST (PA AND LAT)   \n",
      "8            84047.984                CHEST (PA AND LAT)   \n",
      "9            84047.984                CHEST (PA AND LAT)   \n",
      "15          123945.421               CHEST (PORTABLE AP)   \n",
      "27  64348.484000000004               CHEST (PORTABLE AP)   \n",
      "\n",
      "   ViewCodeSequence_CodeMeaning PatientOrientationCodeSequence_CodeMeaning  \\\n",
      "7              antero-posterior                                      Erect   \n",
      "8                       lateral                                      Erect   \n",
      "9                       lateral                                      Erect   \n",
      "15             antero-posterior                                      Erect   \n",
      "27             antero-posterior                                      Erect   \n",
      "\n",
      "    split  \n",
      "7   train  \n",
      "8   train  \n",
      "9   train  \n",
      "15  train  \n",
      "27  train  \n"
     ]
    }
   ],
   "source": [
    "# TEST 3: ------- Test dataset filtering -------\n",
    "filtered_train_tfds, filtered_val_tfds, filtered_test_tfds = myCustomDataLoader.load(['has_label'])\n",
    "batched_tfds = filtered_train_tfds.shuffle(buffer_size=2*BATCH_SIZE).map(_preprocess).batch(BATCH_SIZE)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-03-06 21:14:57.085563: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:14:57.213147: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:14:57.357554: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:14:57.446890: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:14:57.589700: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:14:57.680833: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:14:57.808460: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:14:57.935933: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:14:58.267753: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:14:58.686412: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n"
     ]
    },
    {
     "ename": "InvalidArgumentError",
     "evalue": "{{function_node __wrapped__IteratorGetNext_output_types_3_device_/job:localhost/replica:0/task:0/device:CPU:0}} ValueError: setting an array element with a sequence.\nTypeError: float() argument must be a string or a number, not 'DataFrame'\n\n\nThe above exception was the direct cause of the following exception:\n\n\nTraceback (most recent call last):\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n    return func(device, token, args)\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n    outputs = self._call(device, args)\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n    outputs = [\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n    return ops.convert_to_tensor(value, dtype=dtype)\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n    return func(*args, **kwargs)\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n    return constant(v, dtype=dtype, name=name)\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n    t = convert_to_eager_tensor(value, ctx, dtype)\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n    return ops.EagerTensor(value, ctx.device_name, dtype)\n\nValueError: setting an array element with a sequence.\n\n\n\t [[{{node EagerPyFunc}}]] [Op:IteratorGetNext]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[5], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m# Visualize the images and labels for 1 batch\u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m batch \u001b[38;5;129;01min\u001b[39;00m batched_tfds\u001b[38;5;241m.\u001b[39mtake(\u001b[38;5;241m1\u001b[39m):\n\u001b[1;32m      3\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m i \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mrange\u001b[39m(\u001b[38;5;28mlen\u001b[39m(batch[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mimage\u001b[39m\u001b[38;5;124m'\u001b[39m])):\n\u001b[1;32m      4\u001b[0m         image \u001b[38;5;241m=\u001b[39m batch[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mimage\u001b[39m\u001b[38;5;124m'\u001b[39m][i]\n",
      "File \u001b[0;32m~/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/data/ops/iterator_ops.py:787\u001b[0m, in \u001b[0;36mOwnedIterator.__next__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    785\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m__next__\u001b[39m(\u001b[38;5;28mself\u001b[39m):\n\u001b[1;32m    786\u001b[0m   \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 787\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_next_internal\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    788\u001b[0m   \u001b[38;5;28;01mexcept\u001b[39;00m errors\u001b[38;5;241m.\u001b[39mOutOfRangeError:\n\u001b[1;32m    789\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mStopIteration\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/data/ops/iterator_ops.py:770\u001b[0m, in \u001b[0;36mOwnedIterator._next_internal\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    767\u001b[0m \u001b[38;5;66;03m# TODO(b/77291417): This runs in sync mode as iterators use an error status\u001b[39;00m\n\u001b[1;32m    768\u001b[0m \u001b[38;5;66;03m# to communicate that there is no more data to iterate over.\u001b[39;00m\n\u001b[1;32m    769\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m context\u001b[38;5;241m.\u001b[39mexecution_mode(context\u001b[38;5;241m.\u001b[39mSYNC):\n\u001b[0;32m--> 770\u001b[0m   ret \u001b[38;5;241m=\u001b[39m \u001b[43mgen_dataset_ops\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43miterator_get_next\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    771\u001b[0m \u001b[43m      \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_iterator_resource\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    772\u001b[0m \u001b[43m      \u001b[49m\u001b[43moutput_types\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_flat_output_types\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    773\u001b[0m \u001b[43m      \u001b[49m\u001b[43moutput_shapes\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_flat_output_shapes\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    775\u001b[0m   \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m    776\u001b[0m     \u001b[38;5;66;03m# Fast path for the case `self._structure` is not a nested structure.\u001b[39;00m\n\u001b[1;32m    777\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_element_spec\u001b[38;5;241m.\u001b[39m_from_compatible_tensor_list(ret)  \u001b[38;5;66;03m# pylint: disable=protected-access\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/gen_dataset_ops.py:3017\u001b[0m, in \u001b[0;36miterator_get_next\u001b[0;34m(iterator, output_types, output_shapes, name)\u001b[0m\n\u001b[1;32m   3015\u001b[0m   \u001b[38;5;28;01mreturn\u001b[39;00m _result\n\u001b[1;32m   3016\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m _core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m-> 3017\u001b[0m   \u001b[43m_ops\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mraise_from_not_ok_status\u001b[49m\u001b[43m(\u001b[49m\u001b[43me\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mname\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   3018\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m _core\u001b[38;5;241m.\u001b[39m_FallbackException:\n\u001b[1;32m   3019\u001b[0m   \u001b[38;5;28;01mpass\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py:7215\u001b[0m, in \u001b[0;36mraise_from_not_ok_status\u001b[0;34m(e, name)\u001b[0m\n\u001b[1;32m   7213\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mraise_from_not_ok_status\u001b[39m(e, name):\n\u001b[1;32m   7214\u001b[0m   e\u001b[38;5;241m.\u001b[39mmessage \u001b[38;5;241m+\u001b[39m\u001b[38;5;241m=\u001b[39m (\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m name: \u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;241m+\u001b[39m name \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m \u001b[38;5;28;01melse\u001b[39;00m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m-> 7215\u001b[0m   \u001b[38;5;28;01mraise\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_status_to_exception(e) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m: {{function_node __wrapped__IteratorGetNext_output_types_3_device_/job:localhost/replica:0/task:0/device:CPU:0}} ValueError: setting an array element with a sequence.\nTypeError: float() argument must be a string or a number, not 'DataFrame'\n\n\nThe above exception was the direct cause of the following exception:\n\n\nTraceback (most recent call last):\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n    return func(device, token, args)\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n    outputs = self._call(device, args)\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n    outputs = [\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n    return ops.convert_to_tensor(value, dtype=dtype)\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n    return func(*args, **kwargs)\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n    return constant(v, dtype=dtype, name=name)\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n    t = convert_to_eager_tensor(value, ctx, dtype)\n\n  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n    return ops.EagerTensor(value, ctx.device_name, dtype)\n\nValueError: setting an array element with a sequence.\n\n\n\t [[{{node EagerPyFunc}}]] [Op:IteratorGetNext]"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-03-06 21:14:58.991116: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-03-06 21:14:59.128801: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:14:59.259347: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:14:59.404818: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:14:59.558480: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:14:59.689015: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:14:59.825244: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:14:59.961913: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:15:00.088448: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:15:00.180722: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:15:00.322367: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:15:00.455106: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:15:00.594052: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:15:00.730271: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n",
      "2024-03-06 21:15:00.867210: W tensorflow/core/framework/op_kernel.cc:1818] INVALID_ARGUMENT: ValueError: setting an array element with a sequence.\n",
      "TypeError: float() argument must be a string or a number, not 'DataFrame'\n",
      "\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "\n",
      "Traceback (most recent call last):\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 269, in __call__\n",
      "    return func(device, token, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 147, in __call__\n",
      "    outputs = self._call(device, args)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 163, in _call\n",
      "    outputs = [\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 164, in <listcomp>\n",
      "    _maybe_copy_to_context_device(self._convert(x, dtype=dtype),\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/ops/script_ops.py\", line 131, in _convert\n",
      "    return ops.convert_to_tensor(value, dtype=dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py\", line 183, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/ops.py\", line 1636, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 343, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 267, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 279, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 304, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "\n",
      "  File \"/home/payam/miniconda3/envs/tf2-gpu/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py\", line 102, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "\n",
      "ValueError: setting an array element with a sequence.\n",
      "\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# Visualize the images and labels for 1 batch\n",
    "for batch in batched_tfds.take(1):\n",
    "    for i in range(len(batch['image'])):\n",
    "        image = batch['image'][i]\n",
    "        print(image)\n",
    "        # label_idx = np.where(batch['label'][i] == 1)\n",
    "        # labels = class_names[label_idx]\n",
    "        # info = batch['info'][i].numpy()\n",
    "        # info_dict = {'subject_id': info[0], 'study_id': info[1], 'dicom_id': info[2]}\n",
    "\n",
    "        # # Display the image, label, and info\n",
    "        # plt.imshow(image, cmap='gray')  # Assuming grayscale images\n",
    "        # plt.title(f\"Label: {labels}\")\n",
    "        # plt.show()\n",
    "        # print('patient ^:', info_dict)\n",
    "        # print('\\n')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.18"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
